#!/bin/bash
set -e
CUR_DIR=`pwd`

if [ "${AUTOPKGTEST_TMP}" = "" ] ; then
  AUTOPKGTEST_TMP=$(mktemp -d /tmp/${pkg}-test.XXXXXX)
  trap "rm -rf ${AUTOPKGTEST_TMP}" 0 INT QUIT ABRT PIPE TERM
fi

cd "${AUTOPKGTEST_TMP}"
cp -a ${CUR_DIR}/tests .

export MPLBACKEND=Agg
for py in $(py3versions -s 2> /dev/null)
do
	$py -m pytest -v
done
